(()=>{
"use strict";
const PARTICLE_KEY="japaneseMiniApps_particleWritten_v1";
const VERB_KEY="japaneseMiniApps_verbConjugationWritten_v1";
const ACTIVE_KEY="japaneseMiniApps_grammarActiveMode_v1";
const $id=id=>document.getElementById(id);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const normalize=value=>String(value??"").normalize("NFKC").trim().replace(/[\s　]+/g,"").replace(/[、。，．。！？!?]+$/g,"");
const defaults=()=>({lesson:"all",submode:"practice",language:"zh",pos:0,random:false,order:[],review:"all",results:{},drafts:{},marked:{},startedAt:null,completionSeconds:null});
function load(key){try{return{...defaults(),...JSON.parse(localStorage.getItem(key)||"{}")}}catch(_){return defaults()}}
let active=localStorage.getItem(ACTIVE_KEY)||"cards";
let particleState=load(PARTICLE_KEY),verbState=load(VERB_KEY);
const config={
 "particle-written":{key:PARTICLE_KEY,data:PARTICLE_WRITTEN_QUESTIONS,state:()=>particleState,titleJa:"助詞記述",titleZh:"助詞填空"},
 "verb-conjugation-written":{key:VERB_KEY,data:VERB_CONJUGATION_WRITTEN_QUESTIONS,state:()=>verbState,titleJa:"動詞選択・活用",titleZh:"動詞選擇及活用"}
};
const hiddenFeedback={"particle-written":new Set(),"verb-conjugation-written":new Set()};
const ui={zh:{all:"全部",practice:"練習模式",exam:"考試模式",random:"隨機模式",marked:"已標記",incorrect:"錯題重溫",allQuestions:"全部題目",check:"檢查答案",reveal:"查看答案",hideAnswer:"隱藏答案",previous:"上一題",next:"下一題",reset:"重設進度",correct:"正確",wrong:"錯誤",reviewed:"已查看",accuracy:"正確率",language:"日本語 UI",blankCount:"空格",baseVerb:"指定動詞"},ja:{all:"すべて",practice:"練習モード",exam:"試験モード",random:"ランダム",marked:"マーク",incorrect:"間違いを復習",allQuestions:"全問題",check:"答えを確認",reveal:"答えを見る",hideAnswer:"答えを隠す",previous:"前へ",next:"次へ",reset:"進捗をリセット",correct:"正解",wrong:"不正解",reviewed:"確認済み",accuracy:"正答率",language:"繁體中文 UI",blankCount:"空欄",baseVerb:"指定動詞"}};
function save(mode){const c=config[mode];localStorage.setItem(c.key,JSON.stringify(c.state()))}
function answerKey(mode,s,q){return mode==="particle-written"?`${s.submode}:${q.id}`:q.id}
function migratePracticeReviews(mode){const c=config[mode],s=c.state();let changed=false;c.data.filter(q=>mode==="particle-written"||q.subtype==="practice").forEach(q=>{const k=mode==="particle-written"?`practice:${q.id}`:q.id,r=s.results[k];if(r?.status!=="reviewed")return;const entered=[...(s.drafts[k]||r.answers||[])],attempts=Math.max(1,r.attempts||0);if(mode==="particle-written"){const correct=entered.length===q.answers.length&&entered.every((v,i)=>q.answers[i].accepted.some(a=>normalize(a)===normalize(v)));s.results[k]={status:correct?"correct":"incorrect",attempts,answers:entered,revealed:true}}else{const n=normalize(entered[0]||""),correct=q.acceptedAnswers.some(a=>normalize(a)===n),error=q.commonErrors.find(e=>e.answers.some(a=>normalize(a)===n));s.results[k]=correct?{status:"correct",attempts,answers:entered,revealed:true}:{status:"incorrect",attempts,answers:entered,revealed:true,errorType:error?.type||"wrong-verb",feedbackZh:error?.feedbackZh||"請重新確認動詞選擇及題目空格外已印出的接續。"}}changed=true});if(changed)save(mode)}
function ensureOrder(mode){const c=config[mode],s=c.state(),ids=c.data.map(q=>q.id);if(s.order.length!==ids.length||s.order.some(id=>!ids.includes(id)))s.order=[...ids]}
function ordered(mode){const c=config[mode],s=c.state();ensureOrder(mode);let q=s.order.map(id=>c.data.find(x=>x.id===id)).filter(Boolean);if(mode==="verb-conjugation-written")q=q.filter(x=>x.subtype===s.submode);if(s.lesson!=="all")q=q.filter(x=>x.lesson===Number(s.lesson));if(s.review==="incorrect")q=q.filter(x=>s.results[answerKey(mode,s,x)]?.status==="incorrect");if(s.review==="marked")q=q.filter(x=>s.marked[x.id]);return q}
function stats(mode){const c=config[mode],s=c.state(),eligible=c.data.filter(q=>(mode==="particle-written"||q.subtype===s.submode)&&(s.lesson==="all"||q.lesson===Number(s.lesson))),results=eligible.map(q=>s.results[answerKey(mode,s,q)]).filter(Boolean),correct=results.filter(r=>r.status==="correct").length,incorrect=results.filter(r=>r.status==="incorrect").length,reviewed=results.filter(r=>r.status==="reviewed").length,total=correct+incorrect;return{correct,incorrect,reviewed,accuracy:total?Math.round(correct/total*100):0}}
function capture(mode){const s=config[mode].state(),inputs=[...document.querySelectorAll("[data-written-input]")];if(!inputs.length)return;const q=config[mode].data.find(x=>x.id===inputs[0].dataset.question);if(q)s.drafts[answerKey(mode,s,q)]=inputs.map(x=>x.value);save(mode)}
function shuffle(mode){const s=config[mode].state();s.order=[...config[mode].data.map(q=>q.id)];for(let i=s.order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[s.order[i],s.order[j]]=[s.order[j],s.order[i]]}}
function completeParticle(q,answers){return q.sentenceParts.map((part,i)=>part+(i<q.answers.length?(answers?.[i]||q.answers[i].displayAnswer):"")).join("")}
function questionFeedback(mode,q){const s=config[mode].state(),k=answerKey(mode,s,q),r=s.results[k];if(!r||hiddenFeedback[mode].has(k))return"";const zh=s.language==="zh",labels=zh?{correct:"〇 答對了。",reviewed:"已查看答案；本題不計作答對。",wrongForm:"△ 動詞選擇正確，但活用形不正確。",wrongVerb:"✕ 請重新選擇符合句意的動詞。",tryAgain:"✕ 請再想一想。",hint:"提示",answer:"正確答案",sentence:"完整句子",baseVerb:"基本動詞",requiredForm:"所需形式",grammar:"文法重點",explanation:"解釋",meaning:"中文意思",grammarLink:"查看相關文法卡"}:{correct:"〇 正解です。",reviewed:"答えを確認しました。正解には数えません。",wrongForm:"△ 動詞は正しいですが、活用形が違います。",wrongVerb:"✕ 文の意味に合う動詞をもう一度選んでください。",tryAgain:"✕ もう一度考えてください。",hint:"ヒント",answer:"正解",sentence:"完成文",baseVerb:"基本動詞",requiredForm:"必要な形",grammar:"文法",explanation:"説明",meaning:"中国語訳",grammarLink:"関連文法カードを見る"};if(mode==="particle-written"&&r.status==="incorrect"&&r.attempts===1&&s.submode==="practice"&&!r.revealed)return`<div class="written-feedback bad"><b>${labels.tryAgain}</b><div class="written-hint">${labels.hint}：${escapeHtml(q.hint||q.grammarPoint)}</div></div>`;
 const cls=r.status==="correct"?"ok":r.errorType==="wrong-form"?"warn":"bad";const headline=r.status==="correct"?labels.correct:r.status==="reviewed"?labels.reviewed:r.errorType==="wrong-form"?labels.wrongForm:mode==="verb-conjugation-written"?labels.wrongVerb:labels.tryAgain;
 const answer=mode==="particle-written"?q.answers.map(a=>a.displayAnswer).join("／"):q.displayAnswer;const full=mode==="particle-written"?completeParticle(q):q.sentenceBefore+q.displayAnswer+q.sentenceAfter,grammarCard=WRITTEN_GRAMMAR_CARD[q.id];
 return`<div class="written-feedback ${cls}"><b>${headline}</b>${r.feedbackZh?`<p>${escapeHtml(r.feedbackZh)}</p>`:""}<div class="written-details"><p><b>${labels.answer}：</b><span lang="ja">${escapeHtml(answer)}</span></p><p><b>${labels.sentence}：</b><span lang="ja">${escapeHtml(full)}</span></p>${mode==="verb-conjugation-written"?`<p><b>${labels.baseVerb}：</b><span lang="ja">${escapeHtml(q.baseVerb)}</span>　<b>${labels.requiredForm}：</b>${escapeHtml(q.requiredForm)}</p>`:""}<p><b>${labels.grammar}：</b><span lang="ja">${escapeHtml(q.grammarPoint)}</span></p><p><b>${labels.explanation}：</b>${escapeHtml(q.explanationZh)}</p><p><b>${labels.meaning}：</b>${escapeHtml(WRITTEN_SENTENCE_ZH[q.id])}</p>${Number.isInteger(grammarCard)?`<p class="grammar-card-row"><a class="grammar-card-link" href="japanese_grammar_flashcards.html?card=${grammarCard}&side=back" data-grammar-card>${labels.grammarLink} ↗</a></p>`:""}</div></div>`}
function renderParticleQuestion(q,s,index,total){const k=answerKey("particle-written",s,q),draft=s.drafts[k]||[],r=s.results[k];const sentence=q.sentenceParts.map((part,i)=>{if(i>=q.answers.length)return escapeHtml(part);return`${escapeHtml(part)}<input data-written-input data-question="${q.id}" data-blank="${i}" class="blank-input" lang="ja" inputmode="text" autocomplete="off" aria-label="空欄 ${i+1}" value="${escapeHtml(draft[i]??r?.answers?.[i]??"")}">`}).join("");return`<div class="written-instruction" lang="ja" data-no-furigana>（　）にひらがなを入れなさい。${s.submode==="practice"?`（空欄：${q.answers.length}）`:""}</div><div class="written-sentence" lang="ja" data-no-furigana>${sentence}</div>${questionFeedback("particle-written",q)}`}
function renderVerbQuestion(q,s){const k=answerKey("verb-conjugation-written",s,q),draft=s.drafts[k]?.[0]??s.results[k]?.answers?.[0]??"";const bank=q.subtype==="exam"?VERB_BANK_GROUPS[q.verbBankGroup]:null;return`${bank?`<div class="verb-bank" lang="ja" data-no-furigana><strong>${escapeHtml(bank.instruction)}</strong>${bank.verbs.map(escapeHtml).join("　")}</div>`:`<div class="written-instruction" data-no-furigana><span class="base-verb">${ui[s.language].baseVerb}：${escapeHtml(q.baseVerb)}</span></div>`}<div class="written-sentence" lang="ja" data-no-furigana>${escapeHtml(q.sentenceBefore)}<input data-written-input data-question="${q.id}" data-blank="0" class="verb-input" lang="ja" autocomplete="off" aria-label="解答" value="${escapeHtml(draft)}">${escapeHtml(q.sentenceAfter)}</div>${questionFeedback("verb-conjugation-written",q)}`}
function renderWritten(mode){const c=config[mode],s=c.state(),t=ui[s.language],list=ordered(mode);if(list.length&&s.pos>=list.length)s.pos=0;const q=list[s.pos],st=stats(mode),title=s.language==="ja"?c.titleJa:c.titleZh;const elapsed=s.completionSeconds!=null?`<span class="written-stat">⏱ ${Math.floor(s.completionSeconds/60)}:${String(s.completionSeconds%60).padStart(2,"0")}</span>`:"",currentKey=q?answerKey(mode,s,q):"",hasResult=Boolean(q&&s.results[currentKey]),answerHidden=hasResult&&hiddenFeedback[mode].has(currentKey);
 $id("writtenMode").innerHTML=`<div class="written-top"><div class="written-title">${escapeHtml(title)}</div><div class="segment language-switch"><button data-action="language" class="active">${t.language}</button></div></div><div class="written-top"><div class="lesson-filter">${["all",9,10,11,12].map(n=>`<button class="lesson-btn ${String(s.lesson)===String(n)?"active":""}" data-action="lesson" data-value="${n}">${n==="all"?t.all:`L${n}`}</button>`).join("")}</div><div class="segment"><button data-action="submode" data-value="practice" class="${s.submode==="practice"?"active":""}">${t.practice}</button><button data-action="submode" data-value="exam" class="${s.submode==="exam"?"active":""}">${t.exam}</button></div></div><div class="written-stats"><span class="written-stat">〇 ${t.correct} ${st.correct}</span><span class="written-stat">✕ ${t.wrong} ${st.incorrect}</span><span class="written-stat">👁 ${t.reviewed} ${st.reviewed}</span><span class="written-stat">${t.accuracy} ${st.accuracy}%</span>${elapsed}</div><div class="written-top"><button class="small-btn ${s.random?"active":""}" data-action="random">🔀 ${t.random}${s.random?"：ON":""}</button><div class="review-actions"><button class="review-btn ${s.review==="all"?"active":""}" data-action="review" data-value="all">${t.allQuestions}</button><button class="review-btn incorrect ${s.review==="incorrect"?"active":""}" data-action="review" data-value="incorrect">✕ ${t.incorrect}</button><button class="review-btn marked ${s.review==="marked"?"active":""}" data-action="review" data-value="marked">★ ${t.marked}</button></div></div>${q?`<article class="written-panel"><div class="written-top"><span class="lesson-tag" style="background:#17324d;color:#fff">L${q.lesson}</span><span>${s.pos+1} / ${list.length}</span><button class="mark-btn ${s.marked[q.id]?"active":""}" data-action="mark" aria-label="標記題目">${s.marked[q.id]?"★":"☆"}</button></div>${mode==="particle-written"?renderParticleQuestion(q,s,s.pos,list.length):renderVerbQuestion(q,s)}<div class="written-actions"><button class="small-btn" data-action="${hasResult?"toggle-answer":"reveal"}">${hasResult&&!answerHidden?t.hideAnswer:t.reveal}</button><button class="small-btn active" data-action="check">${t.check}</button></div><div class="written-nav"><button class="small-btn" data-action="move" data-value="-1">← ${t.previous}</button><button class="small-btn" data-action="move" data-value="1">${t.next} →</button></div></article>`:`<div class="written-panel written-empty">この条件に合う問題はありません。</div>`}<button class="reset" data-action="reset">↻ ${t.reset}</button>`;
 Furigana.apply($id("writtenMode"));bind(mode,q)
}
function setActive(mode){if(config[active])capture(active);active=mode;localStorage.setItem(ACTIVE_KEY,active);document.querySelectorAll("[data-grammar-module]").forEach(b=>b.classList.toggle("active",b.dataset.grammarModule===active));const flashcard=$id("flashcardMode"),written=$id("writtenMode");if(flashcard)flashcard.classList.toggle("hidden",active!=="cards");if(written)written.classList.toggle("active",active!=="cards");if(config[active]&&written){const s=config[active].state();if(s.submode==="exam"&&!s.startedAt)s.startedAt=Date.now();renderWritten(active)}}
function checkParticle(q,s){const inputs=[...document.querySelectorAll("[data-written-input]")],values=inputs.map(x=>x.value),k=answerKey("particle-written",s,q);if(s.submode==="exam"&&values.some(v=>!normalize(v))){inputs.find(x=>!normalize(x.value))?.focus();return}const correct=values.every((v,i)=>q.answers[i].accepted.some(a=>normalize(a)===normalize(v))),old=s.results[k]||{},attempts=(old.attempts||0)+1;s.drafts[k]=values;if(correct)s.results[k]={status:"correct",attempts,answers:values};else s.results[k]={status:"incorrect",attempts,answers:values};save("particle-written");renderWritten("particle-written")}
function checkVerb(q,s){const input=document.querySelector("[data-written-input]"),value=input.value,k=answerKey("verb-conjugation-written",s,q);if(!normalize(value)){input.focus();return}s.drafts[k]=[value];const n=normalize(value),correct=q.acceptedAnswers.some(a=>normalize(a)===n),error=q.commonErrors.find(e=>e.answers.some(a=>normalize(a)===n)),old=s.results[k]||{},attempts=(old.attempts||0)+1;s.results[k]=correct?{status:"correct",attempts,answers:[value]}:{status:"incorrect",attempts,answers:[value],errorType:error?.type||"wrong-verb",feedbackZh:error?.feedbackZh||"請重新確認動詞選擇及題目空格外已印出的接續。"};save("verb-conjugation-written");renderWritten("verb-conjugation-written")}
function reveal(mode,q,s){capture(mode);const k=answerKey(mode,s,q),entered=[...(s.drafts[k]||[])],old=s.results[k]||{};if(s.submode!=="practice"){s.results[k]={status:"reviewed",attempts:old.attempts||0,answers:entered};save(mode);renderWritten(mode);return}const attempts=(old.attempts||0)+1;if(mode==="particle-written"){const correct=entered.length===q.answers.length&&entered.every((v,i)=>q.answers[i].accepted.some(a=>normalize(a)===normalize(v)));s.results[k]={status:correct?"correct":"incorrect",attempts,answers:entered,revealed:true}}else{const value=entered[0]||"",n=normalize(value),correct=q.acceptedAnswers.some(a=>normalize(a)===n),error=q.commonErrors.find(e=>e.answers.some(a=>normalize(a)===n));s.results[k]=correct?{status:"correct",attempts,answers:entered,revealed:true}:{status:"incorrect",attempts,answers:entered,revealed:true,errorType:error?.type||"wrong-verb",feedbackZh:error?.feedbackZh||"請重新確認動詞選擇及題目空格外已印出的接續。"}}save(mode);renderWritten(mode)}
function updateExamCompletion(mode){const s=config[mode].state();if(s.submode!=="exam"||!s.startedAt)return;const exam=config[mode].data.filter(q=>(mode==="particle-written"||q.subtype==="exam")&&(s.lesson==="all"||q.lesson===Number(s.lesson)));if(exam.length&&exam.every(q=>s.results[answerKey(mode,s,q)]))s.completionSeconds=Math.max(1,Math.round((Date.now()-s.startedAt)/1000))}
function bind(mode,q){const s=config[mode].state();document.querySelectorAll("[data-action]").forEach(el=>el.addEventListener("click",()=>{const a=el.dataset.action,v=el.dataset.value;if(a==="language"){s.language=s.language==="zh"?"ja":"zh";save(mode);renderWritten(mode)}if(a==="lesson"){capture(mode);s.lesson=v==="all"?"all":Number(v);s.pos=0;s.startedAt=s.submode==="exam"?Date.now():null;s.completionSeconds=null;save(mode);renderWritten(mode)}if(a==="submode"){capture(mode);s.submode=v;s.pos=0;s.review="all";s.startedAt=v==="exam"?Date.now():null;s.completionSeconds=null;save(mode);renderWritten(mode)}if(a==="random"){capture(mode);s.random=!s.random;if(s.random)shuffle(mode);else s.order=config[mode].data.map(x=>x.id);s.pos=0;save(mode);renderWritten(mode)}if(a==="review"){capture(mode);s.review=v;s.pos=0;save(mode);renderWritten(mode)}if(a==="mark"&&q){s.marked[q.id]=!s.marked[q.id];save(mode);renderWritten(mode)}if(a==="move"){capture(mode);const list=ordered(mode);if(list.length)s.pos=(s.pos+Number(v)+list.length)%list.length;save(mode);renderWritten(mode)}if(a==="check"&&q){hiddenFeedback[mode].delete(answerKey(mode,s,q));mode==="particle-written"?checkParticle(q,s):checkVerb(q,s);updateExamCompletion(mode);save(mode)}if(a==="reveal"&&q){hiddenFeedback[mode].delete(answerKey(mode,s,q));reveal(mode,q,s)}if(a==="toggle-answer"&&q){const k=answerKey(mode,s,q);if(hiddenFeedback[mode].has(k))hiddenFeedback[mode].delete(k);else hiddenFeedback[mode].add(k);renderWritten(mode)}if(a==="reset"&&confirm("この練習の進捗だけをリセットしますか。")){const fresh=defaults();hiddenFeedback[mode].clear();if(mode==="particle-written")particleState=fresh;else verbState=fresh;save(mode);renderWritten(mode)}}));
 const inputs=[...document.querySelectorAll("[data-written-input]")];inputs.forEach((input,i)=>{input.addEventListener("input",()=>capture(mode));input.addEventListener("keydown",event=>{if(event.key!=="Enter")return;event.preventDefault();if(i<inputs.length-1)inputs[i+1].focus();else if(q){hiddenFeedback[mode].delete(answerKey(mode,s,q));mode==="particle-written"?checkParticle(q,s):checkVerb(q,s);updateExamCompletion(mode);save(mode)}})})
 document.querySelectorAll("[data-grammar-card]").forEach(link=>link.addEventListener("click",event=>{event.preventDefault();const message=s.language==="zh"?"確定要在新視窗開啟相關的「期終考試文法 Flashcards」嗎？":"関連する「期終考試文法 Flashcards」を新しいウィンドウで開きますか？";if(confirm(message))window.open(link.href,"_blank","noopener,noreferrer")}))
}
document.querySelectorAll("[data-grammar-module]").forEach(b=>b.addEventListener("click",()=>setActive(b.dataset.grammarModule)));
migratePracticeReviews("particle-written");migratePracticeReviews("verb-conjugation-written");ensureOrder("particle-written");ensureOrder("verb-conjugation-written");const standaloneMode=document.body.dataset.writtenMode;setActive(config[standaloneMode]?standaloneMode:(["cards","particle-written","verb-conjugation-written"].includes(active)?active:"cards"));
})();
