const particleQuestion=(id,lesson,sentenceParts,answerStrings,explanationZh,grammarPoint,sourceType,sourceReference,hint)=>({
  id,lesson,mode:"particle-written",sentenceParts,
  answers:answerStrings.map(x=>({accepted:[x],displayAnswer:x})),explanationZh,grammarPoint,
  sourceType,sourceLesson:lesson,sourceReference,hint
});
const PARTICLE_WRITTEN_QUESTIONS=[
// Lesson 9 - Quiz 5 Section V and grammar-note comparison/cause structures.
particleQuestion("l09-particle-001",9,["これと同じ色","、Lサイズの物はありませんか。"],["で"],"「同じ色で」使用「で」連接後面的商品條件。","Nで","school-quiz","Quiz 5 Section V-1","連接兩個商品條件。"),
particleQuestion("l09-particle-002",9,["村上春樹は日本","世界","誇る現代作家です。"],["が","に"],"「日本が世界に誇る」表示日本向世界引以為傲。","NがNに誇る","school-quiz","Quiz 5 Section V-2","誰引以為傲、向哪個範圍展示？"),
particleQuestion("l09-particle-003",9,["青空社は他社","","技術競争","負けました。"],["と","の","に"],"教材把「との」分成兩格：「他社との技術競争」；「競争に負ける」用「に」。","Nとの競争に負ける","school-quiz","Quiz 5 Section V-3","教材把「との」分成兩個空格。"),
particleQuestion("l09-particle-004",9,["オンライン学習は学生の勉強法","大きな影響","与えました。"],["に","を"],"「Nに影響を与える」是固定搭配。","Nに影響を与える","school-quiz","Quiz 5 Section V-4","「影響」前後的固定搭配。"),
particleQuestion("l09-particle-005",9,["香道は茶道","有名ではありませんが、私は香道","茶道に興味があります。"],["ほど","より"],"否定比較用「ほど」，肯定比較基準用「より」。","ほど～ない／より～","school-quiz","Quiz 5 Section VI-1","否定比較和肯定比較使用不同助詞。"),
particleQuestion("l09-particle-006",9,["この町は東京","にぎやかではありません。"],["ほど"],"「AはBほど～ない」表示 A 不如 B。","ほど～ない","grammar-note","L9 Note 3","後面是否定比較。"),
particleQuestion("l09-particle-007",9,["スポーツのあとに飲む水ほどおいしいもの","ありません。"],["は"],"「XほどYはない」表示沒有比 X 更 Y 的事物。","～ほど～はない","grammar-note","L9 Note 4","最高程度比較中的提示助詞。"),
particleQuestion("l09-particle-008",9,["田中先生ほど熱心な先生","いません。"],["は"],"人物最高程度比較使用「Xほど…人はいない」。","～ほど～はいない","grammar-note","L9 Note 4","人物不存在時用「はいません」。"),
particleQuestion("l09-particle-009",9,["大雪が降ったため","、空港が閉鎖されました。"],["に"],"正式原因表達是「ために」。","～ために（原因）","grammar-note","L9 Note 5","正式文章中的原因表達。"),
particleQuestion("l09-particle-010",9,["空港が使えなくなったのは、大雪","ためです。"],["の"],"名詞接原因「ため」時使用「Nのため」。","Nのため","grammar-note","L9 Note 5","名詞與「ため」的接續。"),
particleQuestion("l09-particle-011",9,["ここ","座ってもかまいませんか。"],["に"],"「座る」的落點使用「に」。","場所に座る","adapted","L9 Note 2","動作的落點。"),
particleQuestion("l09-particle-012",9,["部長は何時","会社","お着きですか。"],["に","に"],"時間點及「着く」的到達地均用「に」。","時間に／場所に着く","adapted","L9 Note 1","時間點與到達點。"),
particleQuestion("l09-particle-013",9,["先生はどんなパソコン","お使いですか。"],["を"],"「使う」的受詞用「を」，尊敬語形式不改變助詞。","Nをお使いです","adapted","L9 Note 1","尊敬語仍保留原動詞的格助詞。"),
particleQuestion("l09-particle-014",9,["この島","見る星ほど美しいものはありません。"],["で"],"觀看動作發生的場所用「で」。","場所でV","adapted","L9 Note 4","動作發生的場所。"),
particleQuestion("l09-particle-015",9,["お金があれば、このパソコン","買えたのに。"],["が"],"可能形「買える」的對象在本教材例句中用「が」。","可能形の対象が","grammar-note","L9 Note 6","可能形前的對象助詞。"),

// Lesson 10 - Quiz 6 verb-bank/compound contexts and grammar notes.
particleQuestion("l10-particle-001",10,["もし宝くじ","当たったら、何","しますか。"],["が","を"],"「宝くじが当たる」及「何をする」是自然搭配。","宝くじが当たる／何をする","school-quiz","Quiz 6 Section VI-1","兩個動詞各自要求甚麼助詞？"),
particleQuestion("l10-particle-002",10,["小さな失敗","大きな事故","つながることがあります。"],["が","に"],"「失敗が事故につながる」表示小失敗導致大事故。","NがNにつながる","school-quiz","Quiz 6 Section VI-2","主語和結果方向。"),
particleQuestion("l10-particle-003",10,["このパソコン、電源","入っています。明日、修理","出すつもりです。"],["が","に"],"狀態主語用「が」；送去修理是「修理に出す」。","電源が入る／修理に出す","school-quiz","Quiz 6 Section VI-5","狀態主語與用途。"),
particleQuestion("l10-particle-004",10,["人は誰でも間違い","犯すことがあります","、その後が大切です。"],["を","が"],"「間違いを犯す」；偶爾發生用「ことがある」。","Nを犯す／ことがある","school-quiz","Quiz 6 Section VI-6","固定搭配與「こと」後的助詞。"),
particleQuestion("l10-particle-005",10,["家族","話し合った結果、北海道","行くことにしました。"],["と","へ"],"共同商量的對象用「と」；移動方向可用「へ」。","Nと話し合う／場所へ行く","school-quiz","Quiz 6 Section IX-5","共同動作與移動方向。"),
particleQuestion("l10-particle-006",10,["薬を飲んだから、熱","下がるはずです。"],["が"],"自動詞「下がる」的主語用「が」。","熱が下がる","grammar-note","L10 Note 1","誰／甚麼下降？"),
particleQuestion("l10-particle-007",10,["あんなに練習したのだから、試合","負けるはずがありません。"],["に"],"「試合に負ける」使用「に」。","試合に負ける","grammar-note","L10 Note 1(2)","「負ける」的固定搭配。"),
particleQuestion("l10-particle-008",10,["このエレベーターは、たまに止まること","あります。"],["が"],"「ことがある」表示有時會發生。","ことがある","grammar-note","L10 Note 2","偶爾發生的句型。"),
particleQuestion("l10-particle-009",10,["母の料理は、たまに辛すぎること","あります。"],["も"],"「こともある」可表示也有這種時候。","こともある","grammar-note","L10 Note 2","帶有「也有」語氣。"),
particleQuestion("l10-particle-010",10,["調査した結果、この町の人口","減っていることが分かりました。"],["が"],"自動詞「減る」的主語是人口，用「が」。","人口が減る","grammar-note","L10 Note 3","變化的主語。"),
particleQuestion("l10-particle-011",10,["宿題の作文","書き終わる前に、友達が来ました。"],["を"],"複合動詞「書き終わる」保留「書く」的受詞「を」。","Nを書き終わる","grammar-note","L10 Note 4(2)","複合前的基本動詞是他動詞。"),
particleQuestion("l10-particle-012",10,["料理","塩を入れ忘れました。"],["に"],"把鹽放進料理中，容器／加入處用「に」。","Nに入れる","grammar-note","L10 Note 4(3)","放入的目的地。"),
particleQuestion("l10-particle-013",10,["困ったときこそ、お互い","助け合うことが大切です。"],["に"],"「お互いに」作副詞，表示彼此。","お互いにV合う","adapted","L10 Note 4(3)","互相行動的副詞形式。"),
particleQuestion("l10-particle-014",10,["電車","バスに乗り換えました。"],["から"],"「AからBに乗り換える」表示由 A 轉乘 B。","AからBに乗り換える","grammar-note","L10 Note 4(3)","轉乘的起點。"),
particleQuestion("l10-particle-015",10,["今夜もカレーを食べれば、三日続けて食べたということ","なります。"],["に"],"固定表達為「ということになる」。","ということになる","grammar-note","L10 Reading/Writing","結論表達的固定助詞。"),

// Lesson 11 - Quiz 7 Section IV/VI/VII and grammar notes.
particleQuestion("l11-particle-001",11,["乗り物","酔わない方法","教えてください。"],["に","を"],"「乗り物に酔う」；所教的內容是受詞，用「を」。","乗り物に酔う／Nを教える","school-quiz","Quiz 7 Section IV-5","固定搭配和受詞。"),
particleQuestion("l11-particle-002",11,["地震のあと、電話","全くつながりませんでした","、連絡できませんでした。"],["が","から"],"「電話がつながる」的主語用「が」；原因接續用「から」。","電話がつながる／から","school-quiz","Quiz 7 Section IV-6","自動詞主語與原因。"),
particleQuestion("l11-particle-003",11,["合掌造りの家の中は、いくつか","分けられ、住居","使われています。"],["に","として"],"「いくつかに分ける」表示分成幾部分；用途／身份用「として」。","いくつかに分ける／Nとして","school-quiz","Quiz 7 Sections IV-7, VI-4","分割結果與用途。"),
particleQuestion("l11-particle-004",11,["この湖は天気","水の色が変わり、日本の文化","知られています。"],["によって","として"],"條件差異用「によって」；以某身份被認識用「として」。","Nによって／Nとして","school-quiz","Quiz 7 Section VI-5/6","原因條件與身份。"),
particleQuestion("l11-particle-005",11,["サッカーは見る","するほう","楽しいです。"],["より","が"],"「VるよりVるほうが」比較兩項，較佳一方用「ほうが」。","VるよりVるほうが","school-quiz","Quiz 7 Section VII-1","比較基準與重點一方。"),
particleQuestion("l11-particle-006",11,["これから日本で働く外国人","増えていくでしょう。"],["が"],"變化動詞「増える」的主語用「が」。","Nが増えていく","grammar-note","L11 Note 1","逐漸增加的是甚麼？"),
particleQuestion("l11-particle-007",11,["眠れないなら、薬","飲んだらどうですか。"],["を"],"「薬を飲む」的受詞用「を」。","NをVたらどう","adapted","L11 Note 2","建議句中的基本動詞搭配。"),
particleQuestion("l11-particle-008",11,["漢字は見るより、書いて覚えるほう","忘れにくいです。"],["が"],"比較中較符合評價的一方用「ほうが」。","ほうが","grammar-note","L11 Note 3","「ほう」後表示主語／焦點。"),
particleQuestion("l11-particle-009",11,["新聞","、中国で地震があったらしいです。"],["によると"],"消息來源使用「Nによると」。","Nによると～らしい","grammar-note","L11 Note 5","傳聞的來源。"),
particleQuestion("l11-particle-010",11,["会社の代表","、新商品を説明しました。"],["として"],"資格、身份使用「として」。","Nとして","grammar-note","L11 Note 6","以甚麼身份行動？"),
particleQuestion("l11-particle-011",11,["急いでいたので、鍵","かけずに出かけました。"],["を"],"「鍵をかける」的受詞用「を」，即使接「ずに」也不變。","NをVずに","grammar-note","L11 Note 7(1)","否定接續不改變原動詞的助詞。"),
particleQuestion("l11-particle-012",11,["子どもの熱","下がらず、心配しました。"],["が"],"自動詞「下がる」的主語用「が」。","熱が下がらず","grammar-note","L11 Note 7(2)","下降的是體溫。"),
particleQuestion("l11-particle-013",11,["この寺は今まで二回、火事","焼けています。"],["で"],"歷史事件的原因／手段「火事で焼ける」使用「で」。","Nで焼ける","grammar-note","L11 Note 8","造成燒毀的事件。"),
particleQuestion("l11-particle-014",11,["東京は日本の首都","世界中に知られています。"],["として"],"「Nとして」表示以某種身份或資格；東京以日本首都的身份聞名。","Nとして","adapted","L11 Note 6","以甚麼身份被認識？"),
particleQuestion("l11-particle-015",11,["この漢字","分からなければ、辞書で調べたらどうですか。"],["が"],"「分かる」的對象在本句用「が」。","Nが分かる","adapted","Quiz 7 Section VII-3","「分かる」前常用的助詞。"),

// Lesson 12 - Quiz 8 scanned Sections VI/VII and grammar notes.
particleQuestion("l12-particle-001",12,["庭は公園の隣にあるので、ペットボトル","捨てられて困っています。"],["を"],"間接被動中，被丟棄的物件仍用「を」。","Nを捨てられる","school-quiz","Quiz 8 Section VI-1","被動句中的受影響物件。"),
particleQuestion("l12-particle-002",12,["昨日のセミナーは勉強","なりました。友達","参加を勧められました。"],["に","に"],"「勉強になる」及被動的行為者「友達に勧められる」均用「に」。","勉強になる／NにVられる","school-quiz","Quiz 8 Section VI-2","結果與被動行為者。"),
particleQuestion("l12-particle-003",12,["この部屋は日当たり","悪いので、昼でも暗いです。"],["が"],"形容詞所描述的主語「日当たり」用「が」。","Nが悪い","school-quiz","Quiz 8 Section VI-3","甚麼不好？"),
particleQuestion("l12-particle-004",12,["雨","降られて、会社","遅れました。"],["に","に"],"受害被動的原因／現象用「に」；「会社に遅れる」的目的處亦用「に」。","雨に降られる／Nに遅れる","school-quiz","Quiz 8 Section VI-6","受害來源與遲到的目的處。"),
particleQuestion("l12-particle-005",12,["駅の放送","、乗客の安全性","配慮しています。"],["について","に"],"議題用「について」；「安全性に配慮する」使用「に」。","Nについて／Nに配慮する","school-quiz","Quiz 8 Section VI-7","議題與配慮的對象。"),
particleQuestion("l12-particle-006",12,["急いでいたものです","、鍵を忘れました。"],["から"],"固定原因表達是「ものですから」。","ものだから","grammar-note","L12 Note 1","個人辯解式原因。"),
particleQuestion("l12-particle-007",12,["私は先生","注意されました。"],["に"],"直接被動句的行為者用「に」。","Nに注意される","grammar-note","L12 Note 2(1)","誰作出提醒動作？"),
particleQuestion("l12-particle-008",12,["私は部長","急な仕事","頼まれました。"],["に","を"],"被動句中委託者用「に」，被委託的工作用「を」。","NにNを頼まれる","grammar-note","L12 Note 2(1)","委託者和委託內容。"),
particleQuestion("l12-particle-009",12,["私は泥棒","財布","盗まれました。"],["に","を"],"所有者受害被動中，行為者用「に」，被偷的物件用「を」。","Nに物をVられる","grammar-note","L12 Note 2(1)","偷竊者與被偷的物件。"),
particleQuestion("l12-particle-010",12,["休みの日は洗濯をしたり、掃除","したりします。"],["を"],"列舉動作仍保留「掃除をする」的「を」。","～たり～たり","grammar-note","L12 Note 3","第二個動作的受詞。"),
particleQuestion("l12-particle-011",12,["ドア","開けっぱなしにしないでください。"],["を"],"他動詞「開ける」的受詞用「を」。","NをVっぱなし","grammar-note","L12 Note 4","被打開後放著不管的物件。"),
particleQuestion("l12-particle-012",12,["先生","おかげで、研修を受けられました。"],["の"],"名詞接「おかげで」使用「Nのおかげで」。","Nのおかげで","grammar-note","L12 Note 5(1)","名詞與正面原因的接續。"),
particleQuestion("l12-particle-013",12,["事故","せいで、授業に遅れました。"],["の"],"名詞接負面原因「せいで」使用「Nのせいで」。","Nのせいで","grammar-note","L12 Note 5(2)","名詞與負面原因的接續。"),
particleQuestion("l12-particle-014",12,["隣の部屋","だれかいるみたいです。"],["に"],"存在場所使用「に」。","場所にNがいる","grammar-note","L12 Speaking","人存在的場所。"),
particleQuestion("l12-particle-015",12,["どうか大きな地震","起きませんように。"],["が"],"自動詞「起きる」的主語用「が」。","Nが起きませんように","grammar-note","L12 Reading/Writing","祈願句中事件的主語。")
];
